volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
services:
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    ports:
      - ${CONTAINER_PORT}:9090
    volumes:
      - ./config:/etc/prometheus:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      "--config.file=/etc/prometheus/prometheus.yaml"
  grafana:
    image: grafana/grafana-oss:11.6.0
    container_name: grafana
    ports:
      - ${CONTAINER_PORT_GRA}:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
