services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding
    ports:
      - ${CONTAINER_PORT}:9090
    environment:
      - LD_SUPERUSER_PASSWORD=${LD_SUPERUSER_PASSWORD}
      - LD_SUPERUSER_NAME=${LD_SUPERUSER_NAME}
    volumes:
      - ./data:/etc/linkding/data
    restart: unless-stopped
