services:
  vaultwarden:
    image: vaultwarden/server:1.33.2
    container_name: vaultwarden
    restart: always
    ports:
      - ${CONTAINER_PORT}:80
    environment:
      SINGUPS_ALLOWED: ${SINGUPS_ALLOWED}
    volumes:
      - ./vw-data:/data
