services:
  vikunja:
    image: vikunja/vikunja:0.24.6
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_DATABASE_PATH: ${VIKUNJA_DATABASE_PATH}
    ports:
      - ${CONTAINER_PORT}:3456
    volumes:
      - ./files:/app/vikunja/files
      - ./db:/db
    restart: unless-stopped
