services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.2.1
    restart: unless-stopped
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: ${TUNNEL_DNS_UPSTREAM}
      TUNNEL_DNS_PORT: ${TUNNEL_DNS_PORT}
      TUNNEL_DNS_ADDRESS: ${TUNNEL_DNS_ADDRESS}
    networks:
      pihole:
        ipv4_address: ${ipv4_address}

  pihole:
    container_name: pihole
    hostname: pi-hole-docker
    image: pihole/pihole:2025.03.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${CONTAINER_PORT}:80/tcp
    environment:
      TZ: ${TZ}
      WEBPASSWORD_FILE: ${WEBPASSWORD_FILE}
      IPv6: ${IPv6}
      DHCP_ACTIVE: ${DHCP_ACTIVE}
      WEBUIBOXEDLAYOUT: ${WEBUIBOXEDLAYOUT}
      QUERY_LOGGING: ${QUERY_LOGGING}
      WEBTHEME: ${WEBTHEME}
      PIHOLE_DNS_: ${PIHOLE_DNS_}
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
      - "./web-password:/opt/pihole/web-password"
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: ${ipv4_address_pihole}

networks:
  pihole:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${subnet}
