services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.0.3
    container_name: homepage
    restart: always
    ports:
      - ${CONTAINER_PORT}:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
