services:
  commafeed:
    image: athou/commafeed:5.6.1
    container_name: commafeed
    restart: unless-stopped
    environment:
      - CF_DATABASE_DRIVERCLASS=org.postgresql.Driver
      - CF_DATABASE_URL=jdbc:postgresql://postgresql:5432/commafeed
      - CF_DATABASE_USER=commafeed
      - CF_DATABASE_PASSWORD=commafeed
    volumes:
      - ./data:/commafeed/data
    ports:
      - 8082:8082

  postgresql:
    image: postgres:alpine3.20
    container_name: commafeed_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=commafeed
      - POSTGRES_PASSWORD=commafeed
      - POSTGRES_DB=commafeed
    volumes:
      - ./db:/var/lib/postgresql/db
