services:
  commafeed:
    image: athou/commafeed:5.7.0
    container_name: commafeed
    restart: unless-stopped
    environment:
      - CF_DATABASE_DRIVERCLASS=org.postgresql.Driver
      - CF_DATABASE_URL=jdbc:postgresql://postgresql:5432/commafeed
      - CF_DATABASE_USER=${CF_DATABASE_USER}
      - CF_DATABASE_PASSWORD=${CF_DATABASE_PASSWORD}
    volumes:
      - ./data:/commafeed/data
    ports:
      - ${CONTAINER_PORT}:8082

  postgresql:
    image: postgres:alpine3.20
    container_name: commafeed_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/db
